name: Cross-Browser Testing

on: push
  #schedule:
    # UTC time is setup here i.e. 8:30 AM (daily) which is equal to 2:00 PM IST
    #- cron: '30 8 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browsers: [firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with:
          # Run on all different browsers mentioned in matrix above
          browser: ${{matrix.browsers}}
