name: Cypress Cross-Browser Testing

on: [push]

jobs:
  cross-browser_testing:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        browsers: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          browser: ${{matrix.browsers}}
